services:
  web:
    container_name: webserver
    build: 
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./Web/Flask:/app/Web/Flask:z
    environment:
      - FLASK_APP=.:create_app
      - FLASK_ENV=development
    dns:
      - 8.8.8.8  # Google DNS
      - 1.1.1.1  # Cloudflare DNS
    restart: on-failure
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=cow8_db
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
      - TZ=America/Sao_Paulo
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./Database/scripts:/docker-entrypoint-initdb.d:z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 10
volumes:
  mysql-volume:
    driver: local