services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    build: ./Docker/mysql
    environment:
      - MYSQL_DATABASE=cow8_db
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
      - TZ=America/Sao_Paulo
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./Database/scripts:/docker-entrypoint-initdb.d:z
volumes:
  mysql-volume:
    driver: local